import { Geist_Sans, Geist_Mono } from "geist/font"; // Correct import for Geist fonts
import { Poppins } from 'next/font/google';
import "./globals.css";

// Configure Poppins font
const poppins = Poppins({
  weight: ['400', '600'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins', // Optional: for CSS variables
});

// Configure Geist fonts
const geistSans = Geist_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata for the page
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout component
export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.className} ${geistSans.variable} ${geistMono.variable}`}>
      <body>{children}</body>
    </html>
  );
}