import { GeistSans, GeistMono } from 'geist/font'; // Correct import for Geist fonts
import { Poppins } from 'next/font/google';
import './globals.css';

// Configure Poppins font
const poppins = Poppins({
  weight: ['400', '600'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins', // Optional: for CSS variables
});

// Metadata for the page
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// RootLayout component
export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppins.className} ${GeistSans.variable} ${GeistMono.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}